//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationsAlertManager.Data.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AlertModelContainer : DbContext
    {
        public AlertModelContainer()
            : base("name=AlertModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int DEL_ALRT(Nullable<int> aLRT_ID)
        {
            var aLRT_IDParameter = aLRT_ID.HasValue ?
                new ObjectParameter("ALRT_ID", aLRT_ID) :
                new ObjectParameter("ALRT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT", aLRT_IDParameter);
        }
    
        public virtual int DEL_ALRT_EQPT_ITEM(Nullable<int> aLRT_ID, Nullable<int> aLRT_EQPT_ITEM_ID)
        {
            var aLRT_IDParameter = aLRT_ID.HasValue ?
                new ObjectParameter("ALRT_ID", aLRT_ID) :
                new ObjectParameter("ALRT_ID", typeof(int));
    
            var aLRT_EQPT_ITEM_IDParameter = aLRT_EQPT_ITEM_ID.HasValue ?
                new ObjectParameter("ALRT_EQPT_ITEM_ID", aLRT_EQPT_ITEM_ID) :
                new ObjectParameter("ALRT_EQPT_ITEM_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_EQPT_ITEM", aLRT_IDParameter, aLRT_EQPT_ITEM_IDParameter);
        }
    
        public virtual int DEL_ALRT_FAC(Nullable<int> aLRT_ID, Nullable<int> aLRT_FAC_ID)
        {
            var aLRT_IDParameter = aLRT_ID.HasValue ?
                new ObjectParameter("ALRT_ID", aLRT_ID) :
                new ObjectParameter("ALRT_ID", typeof(int));
    
            var aLRT_FAC_IDParameter = aLRT_FAC_ID.HasValue ?
                new ObjectParameter("ALRT_FAC_ID", aLRT_FAC_ID) :
                new ObjectParameter("ALRT_FAC_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_FAC", aLRT_IDParameter, aLRT_FAC_IDParameter);
        }
    
        public virtual int DEL_ALRT_LIKELY_CAUSE(Nullable<int> aLRT_LIKELY_CAUSE_ID)
        {
            var aLRT_LIKELY_CAUSE_IDParameter = aLRT_LIKELY_CAUSE_ID.HasValue ?
                new ObjectParameter("ALRT_LIKELY_CAUSE_ID", aLRT_LIKELY_CAUSE_ID) :
                new ObjectParameter("ALRT_LIKELY_CAUSE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_LIKELY_CAUSE", aLRT_LIKELY_CAUSE_IDParameter);
        }
    
        public virtual int DEL_ALRT_LIKELY_CAUSE_RMDTN(Nullable<int> aLRT_LIKELY_CAUSE_RMDTN_ID)
        {
            var aLRT_LIKELY_CAUSE_RMDTN_IDParameter = aLRT_LIKELY_CAUSE_RMDTN_ID.HasValue ?
                new ObjectParameter("ALRT_LIKELY_CAUSE_RMDTN_ID", aLRT_LIKELY_CAUSE_RMDTN_ID) :
                new ObjectParameter("ALRT_LIKELY_CAUSE_RMDTN_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_LIKELY_CAUSE_RMDTN", aLRT_LIKELY_CAUSE_RMDTN_IDParameter);
        }
    
        public virtual int DEL_ALRT_PRCS_TYPE(Nullable<int> aLRT_PRCS_TYPE_ID)
        {
            var aLRT_PRCS_TYPE_IDParameter = aLRT_PRCS_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_PRCS_TYPE_ID", aLRT_PRCS_TYPE_ID) :
                new ObjectParameter("ALRT_PRCS_TYPE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_PRCS_TYPE", aLRT_PRCS_TYPE_IDParameter);
        }
    
        public virtual int DEL_ALRT_PRIO_TYPE(Nullable<int> aLRT_PRIO_TYPE_ID)
        {
            var aLRT_PRIO_TYPE_IDParameter = aLRT_PRIO_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_PRIO_TYPE_ID", aLRT_PRIO_TYPE_ID) :
                new ObjectParameter("ALRT_PRIO_TYPE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_PRIO_TYPE", aLRT_PRIO_TYPE_IDParameter);
        }
    
        public virtual int DEL_ALRT_RESP(Nullable<int> aLRT_RESP_ID)
        {
            var aLRT_RESP_IDParameter = aLRT_RESP_ID.HasValue ?
                new ObjectParameter("ALRT_RESP_ID", aLRT_RESP_ID) :
                new ObjectParameter("ALRT_RESP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_RESP", aLRT_RESP_IDParameter);
        }
    
        public virtual int DEL_ALRT_RESP_TYPE(Nullable<int> aLRT_RESP_TYPE_ID)
        {
            var aLRT_RESP_TYPE_IDParameter = aLRT_RESP_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_RESP_TYPE_ID", aLRT_RESP_TYPE_ID) :
                new ObjectParameter("ALRT_RESP_TYPE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_RESP_TYPE", aLRT_RESP_TYPE_IDParameter);
        }
    
        public virtual int DEL_ALRT_RMDTN(Nullable<int> aLRT_RMDTN_ID)
        {
            var aLRT_RMDTN_IDParameter = aLRT_RMDTN_ID.HasValue ?
                new ObjectParameter("ALRT_RMDTN_ID", aLRT_RMDTN_ID) :
                new ObjectParameter("ALRT_RMDTN_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_RMDTN", aLRT_RMDTN_IDParameter);
        }
    
        public virtual int DEL_ALRT_RSLN_TYPE(Nullable<int> aLRT_RSLN_TYPE_ID)
        {
            var aLRT_RSLN_TYPE_IDParameter = aLRT_RSLN_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_RSLN_TYPE_ID", aLRT_RSLN_TYPE_ID) :
                new ObjectParameter("ALRT_RSLN_TYPE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_RSLN_TYPE", aLRT_RSLN_TYPE_IDParameter);
        }
    
        public virtual int DEL_ALRT_SRCE_SYS(Nullable<int> aLRT_SS_ID)
        {
            var aLRT_SS_IDParameter = aLRT_SS_ID.HasValue ?
                new ObjectParameter("ALRT_SS_ID", aLRT_SS_ID) :
                new ObjectParameter("ALRT_SS_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_SRCE_SYS", aLRT_SS_IDParameter);
        }
    
        public virtual int DEL_ALRT_STAT_TYPE(Nullable<int> aLRT_STAT_TYPE_ID)
        {
            var aLRT_STAT_TYPE_IDParameter = aLRT_STAT_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_STAT_TYPE_ID", aLRT_STAT_TYPE_ID) :
                new ObjectParameter("ALRT_STAT_TYPE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_STAT_TYPE", aLRT_STAT_TYPE_IDParameter);
        }
    
        public virtual int DEL_ALRT_TYPE(Nullable<int> aLRT_TYPE_ID)
        {
            var aLRT_TYPE_IDParameter = aLRT_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_TYPE_ID", aLRT_TYPE_ID) :
                new ObjectParameter("ALRT_TYPE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_TYPE", aLRT_TYPE_IDParameter);
        }
    
        public virtual int DEL_ALRT_TYPE_SRCE_SYS(Nullable<int> aLRT_TYPE_SS_ID)
        {
            var aLRT_TYPE_SS_IDParameter = aLRT_TYPE_SS_ID.HasValue ?
                new ObjectParameter("ALRT_TYPE_SS_ID", aLRT_TYPE_SS_ID) :
                new ObjectParameter("ALRT_TYPE_SS_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DEL_ALRT_TYPE_SRCE_SYS", aLRT_TYPE_SS_IDParameter);
        }
    
        public virtual int EXCEPTION_LOGGING(string xCPN_MSG_TXT, string xCPN_TYPE_TXT, string xCPN_SS_TXT, string xCPN_URL_TXT)
        {
            var xCPN_MSG_TXTParameter = xCPN_MSG_TXT != null ?
                new ObjectParameter("XCPN_MSG_TXT", xCPN_MSG_TXT) :
                new ObjectParameter("XCPN_MSG_TXT", typeof(string));
    
            var xCPN_TYPE_TXTParameter = xCPN_TYPE_TXT != null ?
                new ObjectParameter("XCPN_TYPE_TXT", xCPN_TYPE_TXT) :
                new ObjectParameter("XCPN_TYPE_TXT", typeof(string));
    
            var xCPN_SS_TXTParameter = xCPN_SS_TXT != null ?
                new ObjectParameter("XCPN_SS_TXT", xCPN_SS_TXT) :
                new ObjectParameter("XCPN_SS_TXT", typeof(string));
    
            var xCPN_URL_TXTParameter = xCPN_URL_TXT != null ?
                new ObjectParameter("XCPN_URL_TXT", xCPN_URL_TXT) :
                new ObjectParameter("XCPN_URL_TXT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EXCEPTION_LOGGING", xCPN_MSG_TXTParameter, xCPN_TYPE_TXTParameter, xCPN_SS_TXTParameter, xCPN_URL_TXTParameter);
        }
    
        public virtual ObjectResult<GET_ALRT_PRIO_TYPE_Result> GET_ALRT_PRIO_TYPE(Nullable<bool> includeInactive)
        {
            var includeInactiveParameter = includeInactive.HasValue ?
                new ObjectParameter("IncludeInactive", includeInactive) :
                new ObjectParameter("IncludeInactive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALRT_PRIO_TYPE_Result>("GET_ALRT_PRIO_TYPE", includeInactiveParameter);
        }
    
        public virtual ObjectResult<GET_ALRT_RESP_TYPE_Result> GET_ALRT_RESP_TYPE(Nullable<bool> includeInactive)
        {
            var includeInactiveParameter = includeInactive.HasValue ?
                new ObjectParameter("IncludeInactive", includeInactive) :
                new ObjectParameter("IncludeInactive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALRT_RESP_TYPE_Result>("GET_ALRT_RESP_TYPE", includeInactiveParameter);
        }
    
        public virtual ObjectResult<GET_ALRT_RSLN_TYPE_Result> GET_ALRT_RSLN_TYPE(Nullable<bool> includeInactive)
        {
            var includeInactiveParameter = includeInactive.HasValue ?
                new ObjectParameter("IncludeInactive", includeInactive) :
                new ObjectParameter("IncludeInactive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALRT_RSLN_TYPE_Result>("GET_ALRT_RSLN_TYPE", includeInactiveParameter);
        }
    
        public virtual ObjectResult<GET_ALRT_TYPE_Result> GET_ALRT_TYPE(Nullable<bool> includeInactive)
        {
            var includeInactiveParameter = includeInactive.HasValue ?
                new ObjectParameter("IncludeInactive", includeInactive) :
                new ObjectParameter("IncludeInactive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALRT_TYPE_Result>("GET_ALRT_TYPE", includeInactiveParameter);
        }
    
        public virtual ObjectResult<GetAlertByAlertId_Result> GetAlertByAlertId(Nullable<int> aLRT_RESP_ID)
        {
            var aLRT_RESP_IDParameter = aLRT_RESP_ID.HasValue ?
                new ObjectParameter("ALRT_RESP_ID", aLRT_RESP_ID) :
                new ObjectParameter("ALRT_RESP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAlertByAlertId_Result>("GetAlertByAlertId", aLRT_RESP_IDParameter);
        }
    
        public virtual ObjectResult<GetPendingAlertCounts_Result> GetPendingAlertCounts(ObjectParameter lST_READ_DTTM)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPendingAlertCounts_Result>("GetPendingAlertCounts", lST_READ_DTTM);
        }
    
        public virtual ObjectResult<GetResolvedAlerts_Result> GetResolvedAlerts(Nullable<System.DateTime> sTARTDATE)
        {
            var sTARTDATEParameter = sTARTDATE.HasValue ?
                new ObjectParameter("STARTDATE", sTARTDATE) :
                new ObjectParameter("STARTDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetResolvedAlerts_Result>("GetResolvedAlerts", sTARTDATEParameter);
        }
    
        public virtual ObjectResult<GetResponsesByAlertId_Result> GetResponsesByAlertId(Nullable<int> aLRT_ID)
        {
            var aLRT_IDParameter = aLRT_ID.HasValue ?
                new ObjectParameter("ALRT_ID", aLRT_ID) :
                new ObjectParameter("ALRT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetResponsesByAlertId_Result>("GetResponsesByAlertId", aLRT_IDParameter);
        }
    
        public virtual int INSERT_ALRT(string aLRT_SS_NME, Nullable<int> aLRT_SS_ID, string aLRT_SS_KEY_TXT, Nullable<System.DateTime> aLRT_SS_CRE_DTTM, Nullable<int> fAC_ID, string fAC_NME, string fAC_TYPE_CDE, string aLRT_SS_DTL_TXT, Nullable<int> mGMT_PLNT_FAC_ID, ObjectParameter rETVAL)
        {
            var aLRT_SS_NMEParameter = aLRT_SS_NME != null ?
                new ObjectParameter("ALRT_SS_NME", aLRT_SS_NME) :
                new ObjectParameter("ALRT_SS_NME", typeof(string));
    
            var aLRT_SS_IDParameter = aLRT_SS_ID.HasValue ?
                new ObjectParameter("ALRT_SS_ID", aLRT_SS_ID) :
                new ObjectParameter("ALRT_SS_ID", typeof(int));
    
            var aLRT_SS_KEY_TXTParameter = aLRT_SS_KEY_TXT != null ?
                new ObjectParameter("ALRT_SS_KEY_TXT", aLRT_SS_KEY_TXT) :
                new ObjectParameter("ALRT_SS_KEY_TXT", typeof(string));
    
            var aLRT_SS_CRE_DTTMParameter = aLRT_SS_CRE_DTTM.HasValue ?
                new ObjectParameter("ALRT_SS_CRE_DTTM", aLRT_SS_CRE_DTTM) :
                new ObjectParameter("ALRT_SS_CRE_DTTM", typeof(System.DateTime));
    
            var fAC_IDParameter = fAC_ID.HasValue ?
                new ObjectParameter("FAC_ID", fAC_ID) :
                new ObjectParameter("FAC_ID", typeof(int));
    
            var fAC_NMEParameter = fAC_NME != null ?
                new ObjectParameter("FAC_NME", fAC_NME) :
                new ObjectParameter("FAC_NME", typeof(string));
    
            var fAC_TYPE_CDEParameter = fAC_TYPE_CDE != null ?
                new ObjectParameter("FAC_TYPE_CDE", fAC_TYPE_CDE) :
                new ObjectParameter("FAC_TYPE_CDE", typeof(string));
    
            var aLRT_SS_DTL_TXTParameter = aLRT_SS_DTL_TXT != null ?
                new ObjectParameter("ALRT_SS_DTL_TXT", aLRT_SS_DTL_TXT) :
                new ObjectParameter("ALRT_SS_DTL_TXT", typeof(string));
    
            var mGMT_PLNT_FAC_IDParameter = mGMT_PLNT_FAC_ID.HasValue ?
                new ObjectParameter("MGMT_PLNT_FAC_ID", mGMT_PLNT_FAC_ID) :
                new ObjectParameter("MGMT_PLNT_FAC_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_ALRT", aLRT_SS_NMEParameter, aLRT_SS_IDParameter, aLRT_SS_KEY_TXTParameter, aLRT_SS_CRE_DTTMParameter, fAC_IDParameter, fAC_NMEParameter, fAC_TYPE_CDEParameter, aLRT_SS_DTL_TXTParameter, mGMT_PLNT_FAC_IDParameter, rETVAL);
        }
    
        public virtual int ResequenceLikelyCauses(Nullable<int> aLRT_TYPE_ID)
        {
            var aLRT_TYPE_IDParameter = aLRT_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_TYPE_ID", aLRT_TYPE_ID) :
                new ObjectParameter("ALRT_TYPE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ResequenceLikelyCauses", aLRT_TYPE_IDParameter);
        }
    
        public virtual int RethrowError(string errorProcedure)
        {
            var errorProcedureParameter = errorProcedure != null ?
                new ObjectParameter("ErrorProcedure", errorProcedure) :
                new ObjectParameter("ErrorProcedure", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RethrowError", errorProcedureParameter);
        }
    
        public virtual int UPDT_ALRT(ObjectParameter aLRT_ID, Nullable<System.DateTime> aLRT_CRE_DTTM, Nullable<int> aLRT_CRTR_PRSN_BUS_ENTY_ID, Nullable<int> aLRT_RPTD_PRSN_BUS_ENTY_ID, Nullable<int> aLRT_SS_ID, Nullable<int> aLRT_PRIO_TYPE_ID, Nullable<int> aLRT_TYPE_ID, Nullable<System.DateTime> aLRT_RSLN_DTTM, Nullable<int> aLRT_RSLN_TYPE_ID, Nullable<int> rSLV_BY_PRSN_BUS_ENTY_ID, string aLRT_RSLN_DESC, string aLRT_NOTE_TXT, Nullable<System.DateTime> aLRT_SS_CRE_DTTM, string aLRT_SS_DTL_TXT, string uSER_ID)
        {
            var aLRT_CRE_DTTMParameter = aLRT_CRE_DTTM.HasValue ?
                new ObjectParameter("ALRT_CRE_DTTM", aLRT_CRE_DTTM) :
                new ObjectParameter("ALRT_CRE_DTTM", typeof(System.DateTime));
    
            var aLRT_CRTR_PRSN_BUS_ENTY_IDParameter = aLRT_CRTR_PRSN_BUS_ENTY_ID.HasValue ?
                new ObjectParameter("ALRT_CRTR_PRSN_BUS_ENTY_ID", aLRT_CRTR_PRSN_BUS_ENTY_ID) :
                new ObjectParameter("ALRT_CRTR_PRSN_BUS_ENTY_ID", typeof(int));
    
            var aLRT_RPTD_PRSN_BUS_ENTY_IDParameter = aLRT_RPTD_PRSN_BUS_ENTY_ID.HasValue ?
                new ObjectParameter("ALRT_RPTD_PRSN_BUS_ENTY_ID", aLRT_RPTD_PRSN_BUS_ENTY_ID) :
                new ObjectParameter("ALRT_RPTD_PRSN_BUS_ENTY_ID", typeof(int));
    
            var aLRT_SS_IDParameter = aLRT_SS_ID.HasValue ?
                new ObjectParameter("ALRT_SS_ID", aLRT_SS_ID) :
                new ObjectParameter("ALRT_SS_ID", typeof(int));
    
            var aLRT_PRIO_TYPE_IDParameter = aLRT_PRIO_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_PRIO_TYPE_ID", aLRT_PRIO_TYPE_ID) :
                new ObjectParameter("ALRT_PRIO_TYPE_ID", typeof(int));
    
            var aLRT_TYPE_IDParameter = aLRT_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_TYPE_ID", aLRT_TYPE_ID) :
                new ObjectParameter("ALRT_TYPE_ID", typeof(int));
    
            var aLRT_RSLN_DTTMParameter = aLRT_RSLN_DTTM.HasValue ?
                new ObjectParameter("ALRT_RSLN_DTTM", aLRT_RSLN_DTTM) :
                new ObjectParameter("ALRT_RSLN_DTTM", typeof(System.DateTime));
    
            var aLRT_RSLN_TYPE_IDParameter = aLRT_RSLN_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_RSLN_TYPE_ID", aLRT_RSLN_TYPE_ID) :
                new ObjectParameter("ALRT_RSLN_TYPE_ID", typeof(int));
    
            var rSLV_BY_PRSN_BUS_ENTY_IDParameter = rSLV_BY_PRSN_BUS_ENTY_ID.HasValue ?
                new ObjectParameter("RSLV_BY_PRSN_BUS_ENTY_ID", rSLV_BY_PRSN_BUS_ENTY_ID) :
                new ObjectParameter("RSLV_BY_PRSN_BUS_ENTY_ID", typeof(int));
    
            var aLRT_RSLN_DESCParameter = aLRT_RSLN_DESC != null ?
                new ObjectParameter("ALRT_RSLN_DESC", aLRT_RSLN_DESC) :
                new ObjectParameter("ALRT_RSLN_DESC", typeof(string));
    
            var aLRT_NOTE_TXTParameter = aLRT_NOTE_TXT != null ?
                new ObjectParameter("ALRT_NOTE_TXT", aLRT_NOTE_TXT) :
                new ObjectParameter("ALRT_NOTE_TXT", typeof(string));
    
            var aLRT_SS_CRE_DTTMParameter = aLRT_SS_CRE_DTTM.HasValue ?
                new ObjectParameter("ALRT_SS_CRE_DTTM", aLRT_SS_CRE_DTTM) :
                new ObjectParameter("ALRT_SS_CRE_DTTM", typeof(System.DateTime));
    
            var aLRT_SS_DTL_TXTParameter = aLRT_SS_DTL_TXT != null ?
                new ObjectParameter("ALRT_SS_DTL_TXT", aLRT_SS_DTL_TXT) :
                new ObjectParameter("ALRT_SS_DTL_TXT", typeof(string));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT", aLRT_ID, aLRT_CRE_DTTMParameter, aLRT_CRTR_PRSN_BUS_ENTY_IDParameter, aLRT_RPTD_PRSN_BUS_ENTY_IDParameter, aLRT_SS_IDParameter, aLRT_PRIO_TYPE_IDParameter, aLRT_TYPE_IDParameter, aLRT_RSLN_DTTMParameter, aLRT_RSLN_TYPE_IDParameter, rSLV_BY_PRSN_BUS_ENTY_IDParameter, aLRT_RSLN_DESCParameter, aLRT_NOTE_TXTParameter, aLRT_SS_CRE_DTTMParameter, aLRT_SS_DTL_TXTParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_EQPT_ITEM(ObjectParameter aLRT_EQPT_ITEM_ID, Nullable<int> aLRT_ID, string eQPT_ITEM_DESC, string uSER_ID)
        {
            var aLRT_IDParameter = aLRT_ID.HasValue ?
                new ObjectParameter("ALRT_ID", aLRT_ID) :
                new ObjectParameter("ALRT_ID", typeof(int));
    
            var eQPT_ITEM_DESCParameter = eQPT_ITEM_DESC != null ?
                new ObjectParameter("EQPT_ITEM_DESC", eQPT_ITEM_DESC) :
                new ObjectParameter("EQPT_ITEM_DESC", typeof(string));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_EQPT_ITEM", aLRT_EQPT_ITEM_ID, aLRT_IDParameter, eQPT_ITEM_DESCParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_FAC(ObjectParameter aLRT_FAC_ID, Nullable<int> aLRT_ID, Nullable<int> fAC_ID, string fAC_NME, string uSER_ID)
        {
            var aLRT_IDParameter = aLRT_ID.HasValue ?
                new ObjectParameter("ALRT_ID", aLRT_ID) :
                new ObjectParameter("ALRT_ID", typeof(int));
    
            var fAC_IDParameter = fAC_ID.HasValue ?
                new ObjectParameter("FAC_ID", fAC_ID) :
                new ObjectParameter("FAC_ID", typeof(int));
    
            var fAC_NMEParameter = fAC_NME != null ?
                new ObjectParameter("FAC_NME", fAC_NME) :
                new ObjectParameter("FAC_NME", typeof(string));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_FAC", aLRT_FAC_ID, aLRT_IDParameter, fAC_IDParameter, fAC_NMEParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_LIKELY_CAUSE(ObjectParameter aLRT_LIKELY_CAUSE_ID, Nullable<int> aLRT_TYPE_ID, Nullable<int> mGMT_PLNT_FAC_ID, Nullable<int> sEQ_NBR, string cAUSE_DESC, Nullable<System.DateTime> eFTV_DTE, Nullable<System.DateTime> tERM_DTE, string uSER_ID)
        {
            var aLRT_TYPE_IDParameter = aLRT_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_TYPE_ID", aLRT_TYPE_ID) :
                new ObjectParameter("ALRT_TYPE_ID", typeof(int));
    
            var mGMT_PLNT_FAC_IDParameter = mGMT_PLNT_FAC_ID.HasValue ?
                new ObjectParameter("MGMT_PLNT_FAC_ID", mGMT_PLNT_FAC_ID) :
                new ObjectParameter("MGMT_PLNT_FAC_ID", typeof(int));
    
            var sEQ_NBRParameter = sEQ_NBR.HasValue ?
                new ObjectParameter("SEQ_NBR", sEQ_NBR) :
                new ObjectParameter("SEQ_NBR", typeof(int));
    
            var cAUSE_DESCParameter = cAUSE_DESC != null ?
                new ObjectParameter("CAUSE_DESC", cAUSE_DESC) :
                new ObjectParameter("CAUSE_DESC", typeof(string));
    
            var eFTV_DTEParameter = eFTV_DTE.HasValue ?
                new ObjectParameter("EFTV_DTE", eFTV_DTE) :
                new ObjectParameter("EFTV_DTE", typeof(System.DateTime));
    
            var tERM_DTEParameter = tERM_DTE.HasValue ?
                new ObjectParameter("TERM_DTE", tERM_DTE) :
                new ObjectParameter("TERM_DTE", typeof(System.DateTime));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_LIKELY_CAUSE", aLRT_LIKELY_CAUSE_ID, aLRT_TYPE_IDParameter, mGMT_PLNT_FAC_IDParameter, sEQ_NBRParameter, cAUSE_DESCParameter, eFTV_DTEParameter, tERM_DTEParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_LIKELY_CAUSE_RMDTN(ObjectParameter aLRT_LIKELY_CAUSE_RMDTN_ID, Nullable<int> aLRT_LIKELY_CAUSE_ID, Nullable<int> aLRT_RMDTN_ID, Nullable<System.DateTime> eFTV_DTE, Nullable<System.DateTime> tERM_DTE, string uSER_ID)
        {
            var aLRT_LIKELY_CAUSE_IDParameter = aLRT_LIKELY_CAUSE_ID.HasValue ?
                new ObjectParameter("ALRT_LIKELY_CAUSE_ID", aLRT_LIKELY_CAUSE_ID) :
                new ObjectParameter("ALRT_LIKELY_CAUSE_ID", typeof(int));
    
            var aLRT_RMDTN_IDParameter = aLRT_RMDTN_ID.HasValue ?
                new ObjectParameter("ALRT_RMDTN_ID", aLRT_RMDTN_ID) :
                new ObjectParameter("ALRT_RMDTN_ID", typeof(int));
    
            var eFTV_DTEParameter = eFTV_DTE.HasValue ?
                new ObjectParameter("EFTV_DTE", eFTV_DTE) :
                new ObjectParameter("EFTV_DTE", typeof(System.DateTime));
    
            var tERM_DTEParameter = tERM_DTE.HasValue ?
                new ObjectParameter("TERM_DTE", tERM_DTE) :
                new ObjectParameter("TERM_DTE", typeof(System.DateTime));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_LIKELY_CAUSE_RMDTN", aLRT_LIKELY_CAUSE_RMDTN_ID, aLRT_LIKELY_CAUSE_IDParameter, aLRT_RMDTN_IDParameter, eFTV_DTEParameter, tERM_DTEParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_PRCS_TYPE(ObjectParameter aLRT_PRCS_TYPE_ID, string aLRT_PRCS_TYPE_NME, string aLRT_PRCS_TYPE_DESC, Nullable<System.DateTime> eFTV_DTE, Nullable<System.DateTime> tERM_DTE, string uSER_ID)
        {
            var aLRT_PRCS_TYPE_NMEParameter = aLRT_PRCS_TYPE_NME != null ?
                new ObjectParameter("ALRT_PRCS_TYPE_NME", aLRT_PRCS_TYPE_NME) :
                new ObjectParameter("ALRT_PRCS_TYPE_NME", typeof(string));
    
            var aLRT_PRCS_TYPE_DESCParameter = aLRT_PRCS_TYPE_DESC != null ?
                new ObjectParameter("ALRT_PRCS_TYPE_DESC", aLRT_PRCS_TYPE_DESC) :
                new ObjectParameter("ALRT_PRCS_TYPE_DESC", typeof(string));
    
            var eFTV_DTEParameter = eFTV_DTE.HasValue ?
                new ObjectParameter("EFTV_DTE", eFTV_DTE) :
                new ObjectParameter("EFTV_DTE", typeof(System.DateTime));
    
            var tERM_DTEParameter = tERM_DTE.HasValue ?
                new ObjectParameter("TERM_DTE", tERM_DTE) :
                new ObjectParameter("TERM_DTE", typeof(System.DateTime));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_PRCS_TYPE", aLRT_PRCS_TYPE_ID, aLRT_PRCS_TYPE_NMEParameter, aLRT_PRCS_TYPE_DESCParameter, eFTV_DTEParameter, tERM_DTEParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_PRIO_TYPE(ObjectParameter aLRT_PRIO_TYPE_ID, string aLRT_PRIO_TYPE_NME, string aLRT_PRIO_TYPE_DESC, Nullable<int> sTD_AKWLGMT_HOUR_CNT, Nullable<int> sTD_RSLN_HOUR_CNT, Nullable<System.DateTime> eFTV_DTE, Nullable<System.DateTime> tERM_DTE, string uSER_ID)
        {
            var aLRT_PRIO_TYPE_NMEParameter = aLRT_PRIO_TYPE_NME != null ?
                new ObjectParameter("ALRT_PRIO_TYPE_NME", aLRT_PRIO_TYPE_NME) :
                new ObjectParameter("ALRT_PRIO_TYPE_NME", typeof(string));
    
            var aLRT_PRIO_TYPE_DESCParameter = aLRT_PRIO_TYPE_DESC != null ?
                new ObjectParameter("ALRT_PRIO_TYPE_DESC", aLRT_PRIO_TYPE_DESC) :
                new ObjectParameter("ALRT_PRIO_TYPE_DESC", typeof(string));
    
            var sTD_AKWLGMT_HOUR_CNTParameter = sTD_AKWLGMT_HOUR_CNT.HasValue ?
                new ObjectParameter("STD_AKWLGMT_HOUR_CNT", sTD_AKWLGMT_HOUR_CNT) :
                new ObjectParameter("STD_AKWLGMT_HOUR_CNT", typeof(int));
    
            var sTD_RSLN_HOUR_CNTParameter = sTD_RSLN_HOUR_CNT.HasValue ?
                new ObjectParameter("STD_RSLN_HOUR_CNT", sTD_RSLN_HOUR_CNT) :
                new ObjectParameter("STD_RSLN_HOUR_CNT", typeof(int));
    
            var eFTV_DTEParameter = eFTV_DTE.HasValue ?
                new ObjectParameter("EFTV_DTE", eFTV_DTE) :
                new ObjectParameter("EFTV_DTE", typeof(System.DateTime));
    
            var tERM_DTEParameter = tERM_DTE.HasValue ?
                new ObjectParameter("TERM_DTE", tERM_DTE) :
                new ObjectParameter("TERM_DTE", typeof(System.DateTime));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_PRIO_TYPE", aLRT_PRIO_TYPE_ID, aLRT_PRIO_TYPE_NMEParameter, aLRT_PRIO_TYPE_DESCParameter, sTD_AKWLGMT_HOUR_CNTParameter, sTD_RSLN_HOUR_CNTParameter, eFTV_DTEParameter, tERM_DTEParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_RESP(ObjectParameter aLRT_RESP_ID, Nullable<int> aLRT_ID, Nullable<int> aLRT_RESP_TYPE_ID, Nullable<int> rESP_CRE_PRSN_BUS_ENTY_ID, Nullable<System.DateTime> rESP_CRE_DTTM, Nullable<System.DateTime> rESP_CMPL_DTTM, string pM_NBR, string nTWK_NBR, string nTWK_ACTY_NBR, string rESP_DESC, string uSER_ID)
        {
            var aLRT_IDParameter = aLRT_ID.HasValue ?
                new ObjectParameter("ALRT_ID", aLRT_ID) :
                new ObjectParameter("ALRT_ID", typeof(int));
    
            var aLRT_RESP_TYPE_IDParameter = aLRT_RESP_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_RESP_TYPE_ID", aLRT_RESP_TYPE_ID) :
                new ObjectParameter("ALRT_RESP_TYPE_ID", typeof(int));
    
            var rESP_CRE_PRSN_BUS_ENTY_IDParameter = rESP_CRE_PRSN_BUS_ENTY_ID.HasValue ?
                new ObjectParameter("RESP_CRE_PRSN_BUS_ENTY_ID", rESP_CRE_PRSN_BUS_ENTY_ID) :
                new ObjectParameter("RESP_CRE_PRSN_BUS_ENTY_ID", typeof(int));
    
            var rESP_CRE_DTTMParameter = rESP_CRE_DTTM.HasValue ?
                new ObjectParameter("RESP_CRE_DTTM", rESP_CRE_DTTM) :
                new ObjectParameter("RESP_CRE_DTTM", typeof(System.DateTime));
    
            var rESP_CMPL_DTTMParameter = rESP_CMPL_DTTM.HasValue ?
                new ObjectParameter("RESP_CMPL_DTTM", rESP_CMPL_DTTM) :
                new ObjectParameter("RESP_CMPL_DTTM", typeof(System.DateTime));
    
            var pM_NBRParameter = pM_NBR != null ?
                new ObjectParameter("PM_NBR", pM_NBR) :
                new ObjectParameter("PM_NBR", typeof(string));
    
            var nTWK_NBRParameter = nTWK_NBR != null ?
                new ObjectParameter("NTWK_NBR", nTWK_NBR) :
                new ObjectParameter("NTWK_NBR", typeof(string));
    
            var nTWK_ACTY_NBRParameter = nTWK_ACTY_NBR != null ?
                new ObjectParameter("NTWK_ACTY_NBR", nTWK_ACTY_NBR) :
                new ObjectParameter("NTWK_ACTY_NBR", typeof(string));
    
            var rESP_DESCParameter = rESP_DESC != null ?
                new ObjectParameter("RESP_DESC", rESP_DESC) :
                new ObjectParameter("RESP_DESC", typeof(string));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_RESP", aLRT_RESP_ID, aLRT_IDParameter, aLRT_RESP_TYPE_IDParameter, rESP_CRE_PRSN_BUS_ENTY_IDParameter, rESP_CRE_DTTMParameter, rESP_CMPL_DTTMParameter, pM_NBRParameter, nTWK_NBRParameter, nTWK_ACTY_NBRParameter, rESP_DESCParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_RESP_TYPE(ObjectParameter aLRT_RESP_TYPE_ID, string aLRT_RESP_TYPE_NME, string aLRT_RESP_TYPE_DESC, Nullable<System.DateTime> eFTV_DTE, Nullable<System.DateTime> tERM_DTE, string uSER_ID)
        {
            var aLRT_RESP_TYPE_NMEParameter = aLRT_RESP_TYPE_NME != null ?
                new ObjectParameter("ALRT_RESP_TYPE_NME", aLRT_RESP_TYPE_NME) :
                new ObjectParameter("ALRT_RESP_TYPE_NME", typeof(string));
    
            var aLRT_RESP_TYPE_DESCParameter = aLRT_RESP_TYPE_DESC != null ?
                new ObjectParameter("ALRT_RESP_TYPE_DESC", aLRT_RESP_TYPE_DESC) :
                new ObjectParameter("ALRT_RESP_TYPE_DESC", typeof(string));
    
            var eFTV_DTEParameter = eFTV_DTE.HasValue ?
                new ObjectParameter("EFTV_DTE", eFTV_DTE) :
                new ObjectParameter("EFTV_DTE", typeof(System.DateTime));
    
            var tERM_DTEParameter = tERM_DTE.HasValue ?
                new ObjectParameter("TERM_DTE", tERM_DTE) :
                new ObjectParameter("TERM_DTE", typeof(System.DateTime));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_RESP_TYPE", aLRT_RESP_TYPE_ID, aLRT_RESP_TYPE_NMEParameter, aLRT_RESP_TYPE_DESCParameter, eFTV_DTEParameter, tERM_DTEParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_RMDTN(ObjectParameter aLRT_RMDTN_ID, Nullable<int> mGMT_PLNT_FAC_ID, Nullable<int> aLRT_TYPE_ID, Nullable<int> rMDTN_SEQ_NBR, string rMDTN_DESC, Nullable<System.DateTime> eFTV_DTE, Nullable<System.DateTime> tERM_DTE, string uSER_ID)
        {
            var mGMT_PLNT_FAC_IDParameter = mGMT_PLNT_FAC_ID.HasValue ?
                new ObjectParameter("MGMT_PLNT_FAC_ID", mGMT_PLNT_FAC_ID) :
                new ObjectParameter("MGMT_PLNT_FAC_ID", typeof(int));
    
            var aLRT_TYPE_IDParameter = aLRT_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_TYPE_ID", aLRT_TYPE_ID) :
                new ObjectParameter("ALRT_TYPE_ID", typeof(int));
    
            var rMDTN_SEQ_NBRParameter = rMDTN_SEQ_NBR.HasValue ?
                new ObjectParameter("RMDTN_SEQ_NBR", rMDTN_SEQ_NBR) :
                new ObjectParameter("RMDTN_SEQ_NBR", typeof(int));
    
            var rMDTN_DESCParameter = rMDTN_DESC != null ?
                new ObjectParameter("RMDTN_DESC", rMDTN_DESC) :
                new ObjectParameter("RMDTN_DESC", typeof(string));
    
            var eFTV_DTEParameter = eFTV_DTE.HasValue ?
                new ObjectParameter("EFTV_DTE", eFTV_DTE) :
                new ObjectParameter("EFTV_DTE", typeof(System.DateTime));
    
            var tERM_DTEParameter = tERM_DTE.HasValue ?
                new ObjectParameter("TERM_DTE", tERM_DTE) :
                new ObjectParameter("TERM_DTE", typeof(System.DateTime));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_RMDTN", aLRT_RMDTN_ID, mGMT_PLNT_FAC_IDParameter, aLRT_TYPE_IDParameter, rMDTN_SEQ_NBRParameter, rMDTN_DESCParameter, eFTV_DTEParameter, tERM_DTEParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_RSLN(Nullable<int> aLRT_ID, Nullable<System.DateTime> aLRT_RSLN_DTTM, Nullable<int> aLRT_RSLN_TYPE_ID, Nullable<int> rSLV_BY_PRSN_BUS_ENTY_ID, string aLRT_RSLN_DESC, string uSER_ID)
        {
            var aLRT_IDParameter = aLRT_ID.HasValue ?
                new ObjectParameter("ALRT_ID", aLRT_ID) :
                new ObjectParameter("ALRT_ID", typeof(int));
    
            var aLRT_RSLN_DTTMParameter = aLRT_RSLN_DTTM.HasValue ?
                new ObjectParameter("ALRT_RSLN_DTTM", aLRT_RSLN_DTTM) :
                new ObjectParameter("ALRT_RSLN_DTTM", typeof(System.DateTime));
    
            var aLRT_RSLN_TYPE_IDParameter = aLRT_RSLN_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_RSLN_TYPE_ID", aLRT_RSLN_TYPE_ID) :
                new ObjectParameter("ALRT_RSLN_TYPE_ID", typeof(int));
    
            var rSLV_BY_PRSN_BUS_ENTY_IDParameter = rSLV_BY_PRSN_BUS_ENTY_ID.HasValue ?
                new ObjectParameter("RSLV_BY_PRSN_BUS_ENTY_ID", rSLV_BY_PRSN_BUS_ENTY_ID) :
                new ObjectParameter("RSLV_BY_PRSN_BUS_ENTY_ID", typeof(int));
    
            var aLRT_RSLN_DESCParameter = aLRT_RSLN_DESC != null ?
                new ObjectParameter("ALRT_RSLN_DESC", aLRT_RSLN_DESC) :
                new ObjectParameter("ALRT_RSLN_DESC", typeof(string));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_RSLN", aLRT_IDParameter, aLRT_RSLN_DTTMParameter, aLRT_RSLN_TYPE_IDParameter, rSLV_BY_PRSN_BUS_ENTY_IDParameter, aLRT_RSLN_DESCParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_RSLN_TYPE(ObjectParameter aLRT_RSLN_TYPE_ID, string aLRT_RSLN_TYPE_NME, string aLRT_RSLN_TYPE_DESC, Nullable<System.DateTime> eFTV_DTE, Nullable<System.DateTime> tERM_DTE, string uSER_ID)
        {
            var aLRT_RSLN_TYPE_NMEParameter = aLRT_RSLN_TYPE_NME != null ?
                new ObjectParameter("ALRT_RSLN_TYPE_NME", aLRT_RSLN_TYPE_NME) :
                new ObjectParameter("ALRT_RSLN_TYPE_NME", typeof(string));
    
            var aLRT_RSLN_TYPE_DESCParameter = aLRT_RSLN_TYPE_DESC != null ?
                new ObjectParameter("ALRT_RSLN_TYPE_DESC", aLRT_RSLN_TYPE_DESC) :
                new ObjectParameter("ALRT_RSLN_TYPE_DESC", typeof(string));
    
            var eFTV_DTEParameter = eFTV_DTE.HasValue ?
                new ObjectParameter("EFTV_DTE", eFTV_DTE) :
                new ObjectParameter("EFTV_DTE", typeof(System.DateTime));
    
            var tERM_DTEParameter = tERM_DTE.HasValue ?
                new ObjectParameter("TERM_DTE", tERM_DTE) :
                new ObjectParameter("TERM_DTE", typeof(System.DateTime));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_RSLN_TYPE", aLRT_RSLN_TYPE_ID, aLRT_RSLN_TYPE_NMEParameter, aLRT_RSLN_TYPE_DESCParameter, eFTV_DTEParameter, tERM_DTEParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_SRCE_SYS(ObjectParameter aLRT_SS_ID, string aLRT_SS_NME, string aLRT_SS_DESC, Nullable<System.DateTime> eFTV_DTE, Nullable<System.DateTime> tERM_DTE, string uSER_ID)
        {
            var aLRT_SS_NMEParameter = aLRT_SS_NME != null ?
                new ObjectParameter("ALRT_SS_NME", aLRT_SS_NME) :
                new ObjectParameter("ALRT_SS_NME", typeof(string));
    
            var aLRT_SS_DESCParameter = aLRT_SS_DESC != null ?
                new ObjectParameter("ALRT_SS_DESC", aLRT_SS_DESC) :
                new ObjectParameter("ALRT_SS_DESC", typeof(string));
    
            var eFTV_DTEParameter = eFTV_DTE.HasValue ?
                new ObjectParameter("EFTV_DTE", eFTV_DTE) :
                new ObjectParameter("EFTV_DTE", typeof(System.DateTime));
    
            var tERM_DTEParameter = tERM_DTE.HasValue ?
                new ObjectParameter("TERM_DTE", tERM_DTE) :
                new ObjectParameter("TERM_DTE", typeof(System.DateTime));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_SRCE_SYS", aLRT_SS_ID, aLRT_SS_NMEParameter, aLRT_SS_DESCParameter, eFTV_DTEParameter, tERM_DTEParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_STAT_TYPE(ObjectParameter aLRT_STAT_TYPE_ID, string aLRT_STAT_TYPE_NME, string aLRT_STAT_TYPE_DESC, Nullable<System.DateTime> eFTV_DTE, Nullable<System.DateTime> tERM_DTE, string uSER_ID)
        {
            var aLRT_STAT_TYPE_NMEParameter = aLRT_STAT_TYPE_NME != null ?
                new ObjectParameter("ALRT_STAT_TYPE_NME", aLRT_STAT_TYPE_NME) :
                new ObjectParameter("ALRT_STAT_TYPE_NME", typeof(string));
    
            var aLRT_STAT_TYPE_DESCParameter = aLRT_STAT_TYPE_DESC != null ?
                new ObjectParameter("ALRT_STAT_TYPE_DESC", aLRT_STAT_TYPE_DESC) :
                new ObjectParameter("ALRT_STAT_TYPE_DESC", typeof(string));
    
            var eFTV_DTEParameter = eFTV_DTE.HasValue ?
                new ObjectParameter("EFTV_DTE", eFTV_DTE) :
                new ObjectParameter("EFTV_DTE", typeof(System.DateTime));
    
            var tERM_DTEParameter = tERM_DTE.HasValue ?
                new ObjectParameter("TERM_DTE", tERM_DTE) :
                new ObjectParameter("TERM_DTE", typeof(System.DateTime));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_STAT_TYPE", aLRT_STAT_TYPE_ID, aLRT_STAT_TYPE_NMEParameter, aLRT_STAT_TYPE_DESCParameter, eFTV_DTEParameter, tERM_DTEParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_STATUS(Nullable<int> aLRT_ID, string uSER_ID)
        {
            var aLRT_IDParameter = aLRT_ID.HasValue ?
                new ObjectParameter("ALRT_ID", aLRT_ID) :
                new ObjectParameter("ALRT_ID", typeof(int));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_STATUS", aLRT_IDParameter, uSER_IDParameter);
        }
    
        public virtual int UPDT_ALRT_TYPE(ObjectParameter aLRT_TYPE_ID, Nullable<int> aLRT_PRCS_TYPE_ID, string fAC_TYPE_CDE, Nullable<int> mGMT_PLNT_FAC_ID, string aLRT_TYPE_NME, string aLRT_TYPE_DESC, Nullable<System.DateTime> eFTV_DTE, Nullable<System.DateTime> tERM_DTE, string uSER_ID, Nullable<int> aLRT_DFLT_PRIO_TYPE_ID)
        {
            var aLRT_PRCS_TYPE_IDParameter = aLRT_PRCS_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_PRCS_TYPE_ID", aLRT_PRCS_TYPE_ID) :
                new ObjectParameter("ALRT_PRCS_TYPE_ID", typeof(int));
    
            var fAC_TYPE_CDEParameter = fAC_TYPE_CDE != null ?
                new ObjectParameter("FAC_TYPE_CDE", fAC_TYPE_CDE) :
                new ObjectParameter("FAC_TYPE_CDE", typeof(string));
    
            var mGMT_PLNT_FAC_IDParameter = mGMT_PLNT_FAC_ID.HasValue ?
                new ObjectParameter("MGMT_PLNT_FAC_ID", mGMT_PLNT_FAC_ID) :
                new ObjectParameter("MGMT_PLNT_FAC_ID", typeof(int));
    
            var aLRT_TYPE_NMEParameter = aLRT_TYPE_NME != null ?
                new ObjectParameter("ALRT_TYPE_NME", aLRT_TYPE_NME) :
                new ObjectParameter("ALRT_TYPE_NME", typeof(string));
    
            var aLRT_TYPE_DESCParameter = aLRT_TYPE_DESC != null ?
                new ObjectParameter("ALRT_TYPE_DESC", aLRT_TYPE_DESC) :
                new ObjectParameter("ALRT_TYPE_DESC", typeof(string));
    
            var eFTV_DTEParameter = eFTV_DTE.HasValue ?
                new ObjectParameter("EFTV_DTE", eFTV_DTE) :
                new ObjectParameter("EFTV_DTE", typeof(System.DateTime));
    
            var tERM_DTEParameter = tERM_DTE.HasValue ?
                new ObjectParameter("TERM_DTE", tERM_DTE) :
                new ObjectParameter("TERM_DTE", typeof(System.DateTime));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            var aLRT_DFLT_PRIO_TYPE_IDParameter = aLRT_DFLT_PRIO_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_DFLT_PRIO_TYPE_ID", aLRT_DFLT_PRIO_TYPE_ID) :
                new ObjectParameter("ALRT_DFLT_PRIO_TYPE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_TYPE", aLRT_TYPE_ID, aLRT_PRCS_TYPE_IDParameter, fAC_TYPE_CDEParameter, mGMT_PLNT_FAC_IDParameter, aLRT_TYPE_NMEParameter, aLRT_TYPE_DESCParameter, eFTV_DTEParameter, tERM_DTEParameter, uSER_IDParameter, aLRT_DFLT_PRIO_TYPE_IDParameter);
        }
    
        public virtual int UPDT_ALRT_TYPE_SRCE_SYS(ObjectParameter aLRT_TYPE_SS_ID, Nullable<int> aLRT_TYPE_ID, Nullable<int> aLRT_SS_ID, string aLRT_SS_KEY_TXT, Nullable<System.DateTime> eFTV_DTE, Nullable<System.DateTime> tERM_DTE, string uSER_ID)
        {
            var aLRT_TYPE_IDParameter = aLRT_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_TYPE_ID", aLRT_TYPE_ID) :
                new ObjectParameter("ALRT_TYPE_ID", typeof(int));
    
            var aLRT_SS_IDParameter = aLRT_SS_ID.HasValue ?
                new ObjectParameter("ALRT_SS_ID", aLRT_SS_ID) :
                new ObjectParameter("ALRT_SS_ID", typeof(int));
    
            var aLRT_SS_KEY_TXTParameter = aLRT_SS_KEY_TXT != null ?
                new ObjectParameter("ALRT_SS_KEY_TXT", aLRT_SS_KEY_TXT) :
                new ObjectParameter("ALRT_SS_KEY_TXT", typeof(string));
    
            var eFTV_DTEParameter = eFTV_DTE.HasValue ?
                new ObjectParameter("EFTV_DTE", eFTV_DTE) :
                new ObjectParameter("EFTV_DTE", typeof(System.DateTime));
    
            var tERM_DTEParameter = tERM_DTE.HasValue ?
                new ObjectParameter("TERM_DTE", tERM_DTE) :
                new ObjectParameter("TERM_DTE", typeof(System.DateTime));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDT_ALRT_TYPE_SRCE_SYS", aLRT_TYPE_SS_ID, aLRT_TYPE_IDParameter, aLRT_SS_IDParameter, aLRT_SS_KEY_TXTParameter, eFTV_DTEParameter, tERM_DTEParameter, uSER_IDParameter);
        }
    
        public virtual ObjectResult<GetPendingAlertsByPriority_Result> GetPendingAlertsByPriority(Nullable<int> aLRT_PRIO_TYPE_ID)
        {
            var aLRT_PRIO_TYPE_IDParameter = aLRT_PRIO_TYPE_ID.HasValue ?
                new ObjectParameter("ALRT_PRIO_TYPE_ID", aLRT_PRIO_TYPE_ID) :
                new ObjectParameter("ALRT_PRIO_TYPE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPendingAlertsByPriority_Result>("GetPendingAlertsByPriority", aLRT_PRIO_TYPE_IDParameter);
        }
    
        public virtual ObjectResult<GetInProgressAlerts_Result> GetInProgressAlerts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInProgressAlerts_Result>("GetInProgressAlerts");
        }
    }
}
